import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'
import { getCounterValue } from './lib/counter-store'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // These aren't cached, so they'll be fresh whenever the router cache is invalidated
  const counter1 = await getCounterValue(1)
  const counter2 = await getCounterValue(2)
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={'min-h-screen flex flex-col items-center'}
      >
        <nav className="flex gap-4 h-40 items-center justify-center">
          <div className="flex flex-col items-center justify-center gap-2">
            <Link
              href="/counter1"
              className="text-xl font-bold px-4 py-2 bg-orange-600 text-white rounded hover:bg-orange-700"
            >
              Counter 1
            </Link>
            <div className="text-xl font-bold">{counter1}</div>
          </div>
          <div className="flex flex-col items-center justify-center gap-2">
            <Link
              href="/counter2"
              className="text-xl font-bold px-4 py-2 bg-orange-600 text-white rounded hover:bg-orange-700"
            >
              Counter 2
            </Link>
            <div className="text-2xl font-bold">{counter2}</div>
          </div>
        </nav>
        <header />
        {children}
        <footer />
      </body>
    </html>
  )
}
